### ISSUE TITLE
Unhandled Exception: setState() called after dispose(): _DigitalClockState#e9232(lifecycle state: defunct, not mounted)

### ISSUE THREAD

**Issue by hacksics** [caglarylmz/slide_digital_clock#2]
```E/flutter ( 4959): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _DigitalClockState#e9232(lifecycle state: defunct, not mounted)
E/flutter ( 4959): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter ( 4959): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 4959): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter ( 4959): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1197:9)
E/flutter ( 4959): #1      State.setState (package:flutter/src/widgets/framework.dart:1232:6)
E/flutter ( 4959): #2      _DigitalClockState.initState.<anonymous closure> (package:slide_digital_clock/slide_digital_clock.dart:62:7)
E/flutter ( 4959): #3      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 4959): #4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 4959): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 4959): #6      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1024:26)
E/flutter ( 4959): #7      _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter ( 4959): #8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 4959): #9      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1008:26)
E/flutter ( 4959): #10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 4959): #11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 4959): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)```

**Comment by bui3itf0ky00** [comment]
Adding `if (mounted)` before the clock widget ( to make sure that click is not working if it is not being shown on screen) solved It for me

**Comment by caglarylmz** [comment]
Thanks
